version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Gobonoid/glitter-and-gold
    docker:
      - image: circleci/golang:1
    steps:
      - checkout
      - run: make lint test
  tidy:
    working_directory: /go/src/github.com/Gobonoid/glitter-and-gold
    docker:
      - image: circleci/golang:1
    steps:
      - checkout
      - run: go mod tidy && git diff --exit-code

  deploy:
    working_directory: /go/src/github.com/Gobonoid/glitter-and-gold
    docker:
      - image: circleci/golang:1
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.05.0-ce
      - run: make lint test
      - run: make ci-docker-build
    #  - run: make ci-kubernetes-push

workflows:
  version: 2
  development:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - tidy:
          filters:
            branches:
              ignore: master

  deployment:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
